development:
  adapter: postgresql
  encoding: unicode
  database: raincoat_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: raincoat_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: raincoat_production
  pool: 5